import streamlit as st
import google.generativeai as genai
from PIL import Image
import requests
import io
import base64

# --- 1. INITIAL SETUP ---
st.set_page_config(page_title="JARVIS V64 PRO", page_icon="🤖", layout="wide")

# API Keys (Directly using your provided keys for ease)
GEMINI_KEY = "AIzaSyDB5QbDVJSrurd0G7lXUHRZVpRPqxSdv8c"
STABILITY_KEY = "sk-dBrp8z3MiVb03Qt5NooKENix0ljoo1I8fC0tgMPBZiU2MjYh"

genai.configure(api_key=GEMINI_KEY)

# --- 2. STYLING (Royal Blue & Glassmorphism) ---
st.markdown("""
    <style>
    .stApp { background: linear-gradient(135deg, #021B79 0%, #0575E6 100%); color: white; }
    .main-box { background: rgba(255, 255, 255, 0.1); backdrop-filter: blur(10px); border-radius: 25px; padding: 30px; border: 1px solid rgba(255, 255, 255, 0.2); }
    .stButton>button { border-radius: 30px; background: white !important; color: #021B79 !important; font-weight: bold !important; width: 100%; border: none; height: 3em; }
    </style>
    """, unsafe_allow_html=True)

# --- 3. SESSION MEMORY ---
if "user_name" not in st.session_state: st.session_state.user_name = None

# --- 4. LANDING PAGE ---
if not st.session_state.user_name:
    _, col2, _ = st.columns([1, 2, 1])
    with col2:
        st.markdown("<div class='main-box'>", unsafe_allow_html=True)
        st.title("🤖 JARVIS V64")
        st.write("The Royal AI Assistant for Sir Dilansh Jain")
        u_name = st.text_input("State your identity, Sir:", placeholder="Type your name...")
        if st.button("INITIALIZE"):
            if u_name:
                st.session_state.user_name = u_name
                st.rerun()
        st.markdown("</div>", unsafe_allow_html=True)

# --- 5. MAIN DASHBOARD ---
else:
    st.sidebar.title(f"Sir {st.session_state.user_name}")
    st.sidebar.success("Status: Online")
    
    tab_chat, tab_art = st.tabs(["🧠 INTELLIGENCE", "🎨 ART STUDIO"])

    # Chat & Vision Tab
    with tab_chat:
        st.subheader("Neural Link (Chat & Vision)")
        uploaded_file = st.file_uploader("Upload an Image to analyze", type=['png', 'jpg', 'jpeg'])
        user_input = st.chat_input("Speak your command, Sir...")

        if user_input:
            st.chat_message("user").write(user_input)
            with st.chat_message("assistant"):
                model = genai.GenerativeModel('gemini-1.5-flash')
                if uploaded_file:
                    img = Image.open(uploaded_file)
                    response = model.generate_content([f"User: {st.session_state.user_name}. {user_input}", img])
                else:
                    response = model.generate_content(f"You are Jarvis. Owner: Dilansh. Reply to: {user_input}")
                st.markdown(response.text)

    # Art Generation Tab
    with tab_art:
        st.subheader("Creative Synthesis")
        art_prompt = st.text_area("Describe the masterpiece you want to create...")
        if st.button("CREATE IMAGE"):
            if art_prompt:
                with st.spinner("Synthesizing pixels..."):
                    url = "https://api.stability.ai/v1/generation/stable-diffusion-v1-6/text-to-image"
                    headers = {"Accept": "application/json", "Authorization": f"Bearer {STABILITY_KEY}"}
                    body = {"text_prompts": [{"text": art_prompt}], "cfg_scale": 7, "height": 512, "width": 512, "samples": 1}
                    
                    res = requests.post(url, headers=headers, json=body)
                    if res.status_code == 200:
                        img_data = base64.b64decode(res.json()["artifacts"][0]["base64"])
                        st.image(Image.open(io.BytesIO(img_data)), caption="Generated by JARVIS")
                    else:
                        st.error(f"Error {res.status_code}: Limits reached or API issue.")
            else:
                st.warning("Please provide a prompt first.")

    if st.sidebar.button("Logout"):
        st.session_state.user_name = None
        st.rerun()
